# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='photos.tags')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Uploader')),
            ],
        ),
    ]
